# Generated by Django 3.0.3 on 2020-04-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200422_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enther the language used in the book (e.g. English)', max_length=200),
        ),
    ]
